package ru.sfedu.shopproject.model.entities;

/**
 * Enum StatusType
 *
 *
 * @author Максим
 */
public enum StatusType{
    UNDEFINED, SUCCESS, ERROR, ID_NOT_EXIST, FAIL, LOGIN_EXIST, LOGIN_NOT_EXIST,
    DEPENDENCIES_NOT_EXIST, PURCHASES_NOT_FOUND, ID_ALLREADY_EXIST, DEPENDENCIES_EXISTED,
    WRONG_TYPE, TITLE_NOT_EXIST, STATUS_NOT_SOLD, SQL_INTEGRITY_CONSTRAIN_EXCEPTION, COMMUNICATIONS_EXCEPTION,

} 
